title:
  x: 90
  y: 850
  width: 700
  height: 50
  font_size: 22
  align: center

art:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050

banner:
  x: 67.5
  y: 37.5
  width: 120
  height: 150

continent:
  x: 87.5
  y: 57.5
  width: 80
  height: 80

cost:
  x: 87.5
  y: 207.5
  width: 110
  height: 110

prestige:
  x: 652.5
  y: 57.5
  width: 130
  height: 130
  align: right

description:
  x: 75
  y: 880
  width: 675
  height: 275
  valign: middle
  align: center
  font_size: 8
desc: # alias
  extends: description

type:
  x: 90
  y: 955
  width: 645
  height: 50
  align: center

lower_right:
  x: 675
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 75
  y: 975
  width: 75
  height: 75
  font_size: 6
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 5
  align: center
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
#cut:
  x: 0
  y: 0
  width: 750
  height: 1050